### ISSUE TITLE
PHP Code Not Syntax Highlighting

### ISSUE THREAD

**Issue by brussell-tfl** [duowb/look-folding-code#1]
Hey great tool! It doesn't seem to be syntax highlighting for my PHP code though. The HTML highlights just fine.

**Comment by duowb** [comment]
Ok, I'll have a look at the compatibility when I have time, but could you provide a code snippet?
😊

**Comment by brussell-tfl** [comment]
Sure here's an example. Applies to any working PHP code, and it also appears to happening for JavaScript and CSS as well, so it's only been syntax highlighting the HTML. Thanks!
![example-capture](https://github.com/user-attachments/assets/a2a02811-462d-4453-817b-a527499420fc)

**Comment by duowb** [comment]
Hi,The new version [`0.0.1`](https://github.com/duowb/look-folding-code/releases/tag/v0.0.1) has been released. Give it a try

**Comment by brussell-tfl** [comment]
Sweet, that works better. Thanks!
